//customers
export const CUSTOMER_LOADING = 'CUSTOMER_LOADING'
export const CUSTOMER_SAVED = 'CUSTOMER_SAVED'
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR'
export const CODE_REQUEST_SENT = 'CODE_REQUEST_SENT'
export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const CODE_VERIFIED= 'CODE_VERIFIED'
export const CODE_ERROR = 'CODE_ERROR'